<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TeacherGroupsManager.Core\TeacherGroupsManager.Core.csproj" />
    <ProjectReference Include="..\TeacherGroupsManager.Data\TeacherGroupsManager.Data.csproj" />
    <ProjectReference Include="..\TeacherGroupsManager.Dtos\TeacherGroupsManager.Dtos.csproj" />
    <ProjectReference Include="..\TeacherGroupsManager.Shared\TeacherGroupsManager.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
