<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\TeacherGroupsManager.Services\TeacherGroupsManager.Services.csproj" />
    <ProjectReference Include="..\TeacherGroupsManager.Dtos\TeacherGroupsManager.Dtos.csproj" />
    <ProjectReference Include="..\TeacherGroupsManager.Shared\TeacherGroupsManager.Shared.csproj" />
    <ProjectReference Include="..\TeacherGroupsManager.Data\TeacherGroupsManager.Data.csproj" />
    <ProjectReference Include="..\TeacherGroupsManager.Core\TeacherGroupsManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
